// Places from the shared Google Maps list "Argentina 2026" (snapshot 2026-10-06; accommodation pins left out on purpose).
// img: file in img/places/ ('../x' = img/x.jpg). own: the photo shows the place itself (otherwise an illustrative food/wine photo).
const MAPS_LIST_URL = 'https://maps.app.goo.gl/XVR6nkKL4ubpQaFu5';

const PLACE_CATS = {
  parrilla: ['🥩', 'Parrilla'], pizza: ['🍕', 'Pizza'], etterem: ['🍽️', 'Étterem'], piac: ['🛒', 'Piac'], kave: ['☕', 'Kávé & reggeli'],
  fagyi: ['🍦', 'Fagyi'], bar: ['🍸', 'Bár'], bor: ['🍷', 'Borászat'], latnivalo: ['🏛️', 'Látnivaló'], kirandulas: ['⛰️', 'Kirándulás'],
};
const FOOD_CATS = ['parrilla', 'pizza', 'etterem', 'piac', 'kave', 'fagyi', 'bar', 'bor'];

const PLACE_LIST = [
  {"name": "Don Julio Parrilla", "addr": "Guatemala 4691, Palermo", "c": "ba", "cat": "parrilla", "area": "Palermo Soho", "d": "A város talán leghíresebb parrillája, rendszeresen szerepel a Latin America’s 50 Best listán. Foglalni érdemes!", "img": "don_julio", "own": 1, "m": "don julio", "top": 1},
  {"name": "La Cabrera", "addr": "José A. Cabrera 5100", "c": "ba", "cat": "parrilla", "area": "Palermo", "d": "Hatalmas adagok, a steak mellé egy csomó kis köretes tálka jár.", "img": "la_cabrera", "own": 1, "m": "la cabrera", "top": 1},
  {"name": "Fogón Asado", "addr": "Uriarte 1423", "c": "ba", "cat": "parrilla", "area": "Palermo", "d": "Asado-élmény: többfogásos menü a tűz körül, a séfek előtted sütik. Foglalással.", "img": "th_asado", "top": 1},
  {"name": "Hierro Parrilla San Telmo", "addr": "Bolívar 970", "c": "ba", "cat": "parrilla", "area": "San Telmo", "d": "Parrilla San Telmóban – jó választás a vasárnapi bolhapiac után.", "img": "th_steak", "m": "san te[lm]{2}o"},
  {"name": "Parrilla Peña", "addr": "Rodríguez Peña 682", "c": "ba", "cat": "parrilla", "area": "Centro", "d": "Régi vágású, klasszikus belvárosi parrilla.", "img": "th_asado"},
  {"name": "El Ferroviario", "addr": "Av. Reservistas Argentinos 219", "c": "ba", "cat": "parrilla", "area": "Liniers", "d": "Nagy, népszerű helyi parrilla a város szélén – messze van, de igazi porteño hangulat.", "img": "th_asado"},
  {"name": "La Carnicería", "addr": "Thames 2317", "c": "ba", "cat": "parrilla", "area": "Palermo", "d": "Modern parrilla Palermóban.", "img": "th_steak"},
  {"name": "José el Carnicero", "addr": "Thames 2316", "c": "ba", "cat": "parrilla", "area": "Palermo", "d": "Húsos hely a La Carnicería szomszédságában.", "img": "th_steak"},
  {"name": "Chori", "addr": "Thames 1653", "c": "ba", "cat": "etterem", "area": "Palermo", "d": "Choripánra szakosodott hely – a kolbászos szendvics feljavított változatban.", "img": "th_chori"},
  {"name": "Güerrín", "addr": "Av. Corrientes 1368", "c": "ba", "cat": "pizza", "area": "Centro · Corrientes", "d": "1932 óta működő legendás pizzéria. Vastag, sajtos porteño pizza, akár állva a pultnál.", "img": "guerrin", "own": 1, "top": 1},
  {"name": "La Mezzetta", "addr": "Av. Álvarez Thomas 1321", "c": "ba", "cat": "pizza", "area": "Colegiales", "d": "Híres a fugazzetájáról (hagymás, sajtos pizza). Inkább helyi, mint turistás.", "img": "th_pizza"},
  {"name": "La Cocina", "addr": "Av. Pueyrredón 1508", "c": "ba", "cat": "etterem", "area": "Recoleta", "d": "Kis hely, empanadákért érdemes betérni.", "img": "th_empanada"},
  {"name": "Picarón", "addr": "Av. Dorrego 866", "c": "ba", "cat": "etterem", "area": "Villa Crespo", "d": "Étterem a listáról.", "img": "th_steak"},
  {"name": "Corte Comedor", "addr": "Av. Olazábal 1391", "c": "ba", "cat": "etterem", "area": "Belgrano", "d": "Étterem a listáról.", "img": "th_steak"},
  {"name": "Evelia", "addr": "Campos Salles 1712", "c": "ba", "cat": "etterem", "area": "Núñez", "d": "Étterem a listáról.", "img": "th_steak"},
  {"name": "Mercado de San Telmo", "addr": "Defensa 963", "c": "ba", "cat": "piac", "area": "San Telmo", "d": "Fedett vásárcsarnok rengeteg kajálós standdal – vasárnap a bolhapiac mellé tökéletes.", "img": "mercado_st", "own": 1, "m": "san te[lm]{2}o"},
  {"name": "Café Tortoni", "addr": "Av. de Mayo 825", "c": "ba", "cat": "kave", "area": "Avenida de Mayo", "d": "1858 óta működő, a város legrégebbi kávéháza. Sokszor sorban kell állni.", "img": "tortoni", "own": 1, "top": 1},
  {"name": "Full City Coffee House", "addr": "Av. Córdoba 4080", "c": "ba", "cat": "kave", "area": "Palermo / Almagro", "d": "Specialty kávézó.", "img": "th_coffee"},
  {"name": "All Saints Café", "addr": "Belgrano", "c": "ba", "cat": "kave", "area": "Belgrano", "d": "Kávézó a listáról.", "img": "th_coffee"},
  {"name": "Finde Heladería", "addr": "Dr. Emilio Ravignani 1949", "c": "ba", "cat": "fagyi", "area": "Palermo", "d": "Fagyizó Palermóban.", "img": "th_icecream"},
  {"name": "Sui Gelé", "addr": "Gorriti 5023", "c": "ba", "cat": "fagyi", "area": "Palermo Soho", "d": "Fagyizó Palermo Sohóban.", "img": "th_icecream"},
  {"name": "Rapanui", "addr": "Malabia 2014", "c": "ba", "cat": "fagyi", "area": "Palermo", "d": "Csokoládé- és fagyibolt.", "img": "th_icecream", "top": 1, "n": "Franui – csokiba mártott málna"},
  {"name": "Cadore", "addr": "Av. Corrientes 1695", "c": "ba", "cat": "fagyi", "area": "Centro · Corrientes", "d": "Klasszikus olasz-argentin gelateria a Corrientesen.", "img": "cadore", "own": 1, "top": 1, "n": "Dulce de leche fagyi"},
  {"name": "Frank’s Bar", "addr": "Arévalo 1445", "c": "ba", "cat": "bar", "area": "Palermo Hollywood", "d": "Speakeasy koktélbár – a bejárat rejtett.", "img": "th_beer"},
  {"name": "Presidente Bar", "addr": "Av. Pres. Manuel Quintana 188", "c": "ba", "cat": "bar", "area": "Recoleta", "d": "Elegáns koktélbár Recoletában.", "img": "th_beer"},
  {"name": "Backroom Bar", "addr": "Jorge Luis Borges 1975", "c": "ba", "cat": "bar", "area": "Palermo Soho", "d": "Bár Palermo Sohóban.", "img": "th_beer"},
  {"name": "Strange Brewing", "addr": "Delgado 658", "c": "ba", "cat": "bar", "area": "Colegiales", "d": "Kézműves sörfőzde és bár.", "img": "th_beer"},
  {"name": "Zonda, Cocina de Paisaje", "addr": "San Martín 1745, Mayor Drummond", "c": "mendoza", "cat": "etterem", "area": "Luján de Cuyo", "d": "Fine dining a borvidéken – foglalva: okt. 14., 13:00, 6 fogásos menü.", "img": "../vineyard_road", "m": "zonda", "top": 1},
  {"name": "1884 Restaurant", "addr": "Belgrano 1188, Godoy Cruz", "c": "mendoza", "cat": "etterem", "area": "Godoy Cruz", "d": "Francis Mallmann tűzön sütős étterme egy régi borászat épületében.", "img": "th_asado", "top": 1},
  {"name": "Casa Vigil (El Enemigo)", "addr": "Videla Aranda 7008, Maipú", "c": "mendoza", "cat": "bor", "area": "Maipú (Chachingo)", "d": "Alejandro Vigil borászata és étterme – bor és vacsora a szőlők között.", "img": "../vineyard_sunset", "top": 1},
  {"name": "Abrasado", "addr": "Av. de Acceso Este 1360", "c": "mendoza", "cat": "parrilla", "area": "Mendoza (Los Toneles)", "d": "Parrilla a Los Toneles borászatban.", "img": "th_steak", "m": "abrasado|toneles"},
  {"name": "Restaurant Centauro", "addr": "Av. Perú 1156", "c": "mendoza", "cat": "etterem", "area": "Mendoza centrum", "d": "Vacsoraötlet a belvárosban.", "img": "th_steak", "m": "centauro"},
  {"name": "Mercado Central", "addr": "Av. Las Heras 279", "c": "mendoza", "cat": "piac", "area": "Mendoza centrum", "d": "Vásárcsarnok sok olcsó kajálós standdal – gyors ebédre.", "img": "mercado_mza", "own": 1, "m": "mercado central"},
  {"name": "Monono", "addr": "Olascoaga 780", "c": "mendoza", "cat": "kave", "area": "Mendoza centrum", "d": "Reggeliző / kávézó.", "img": "th_coffee", "m": "monono"},
  {"name": "La Vene", "addr": "Av. Juan B. Justo 102", "c": "mendoza", "cat": "kave", "area": "Mendoza centrum", "d": "Reggeliző / kávézó.", "img": "th_coffee", "m": "la vene"},
  {"name": "Planta Uno", "addr": "Ceretti 244, Godoy Cruz", "c": "mendoza", "cat": "etterem", "area": "Godoy Cruz", "d": "Étterem a listáról.", "img": "th_empanada"},
  {"name": "La Finquita 1920", "addr": "Manuel Cruz Videla 450, Maipú", "c": "mendoza", "cat": "etterem", "area": "Maipú", "d": "Étterem a maipúi borvidéken.", "img": "../vineyard_road"},
  {"name": "Corazón de Lunlunta", "addr": "Franklin Villanueva 3826", "c": "mendoza", "cat": "etterem", "area": "Lunlunta (Maipú)", "d": "Étterem a borvidéken.", "img": "../vineyard_road"},
  {"name": "Gómez Rooftop", "addr": "Garibaldi 7, Piso 10", "c": "mendoza", "cat": "bar", "area": "Mendoza centrum", "d": "Tetőterasz-bár a 10. emeleten, kilátással a városra.", "img": "th_beer", "m": "gómez|gomez"},
  {"name": "La Central Vermutería", "addr": "Av. Bartolomé Mitre 794", "c": "mendoza", "cat": "bar", "area": "Mendoza centrum", "d": "Vermutbár – a helyi aperitif-kultúra.", "img": "../vineyard_wine", "m": "vermut"},
  {"name": "La Gloria Cantina Cool", "addr": "Mitre 1541, Chacras de Coria", "c": "mendoza", "cat": "bar", "area": "Chacras de Coria", "d": "Kantin / bár Chacras de Coriában.", "img": "th_beer"},
  {"name": "Willys Bar", "addr": "Mitre 1371, Chacras de Coria", "c": "mendoza", "cat": "bar", "area": "Chacras de Coria", "d": "Bár Chacras de Coriában.", "img": "th_beer"},
  {"name": "oYE bar", "addr": "Viamonte 5224, Chacras de Coria", "c": "mendoza", "cat": "bar", "area": "Chacras de Coria", "d": "Bár Chacras de Coriában.", "img": "th_beer"},
  {"name": "Daukos", "addr": "Darragueira 1551, Chacras de Coria", "c": "mendoza", "cat": "etterem", "area": "Chacras de Coria", "d": "Étterem a listáról.", "img": "th_empanada"},
  {"name": "Chirivia", "addr": "Potrerillos", "c": "mendoza", "cat": "etterem", "area": "Potrerillos", "d": "Étterem a hegyekben, Potrerillosnál – jó megálló az Andok felé.", "img": "potrerillos"},
  {"name": "Bodega Viamonte", "addr": "Viamonte 962, Luján de Cuyo", "c": "mendoza", "cat": "bor", "area": "Luján de Cuyo", "d": "Naplementés borkóstoló – okt. 16., 19:00.", "img": "../vineyard_sunset", "m": "viamonte", "top": 1},
  {"name": "Durigutti Family Winemakers", "addr": "Pasaje de la Reta s/n, Las Compuertas", "c": "mendoza", "cat": "bor", "area": "Las Compuertas", "d": "Családi borászat Luján de Cuyóban.", "img": "../grapes"},
  {"name": "Bodega Kaiken", "addr": "Roque Sáenz Peña 5516, Vistalba", "c": "mendoza", "cat": "bor", "area": "Vistalba", "d": "Borászat Luján de Cuyóban.", "img": "../vineyard_road"},
  {"name": "Bodega Vistalba", "addr": "Roque Sáenz Peña 3531, Vistalba", "c": "mendoza", "cat": "bor", "area": "Vistalba", "d": "Borászat Luján de Cuyóban.", "img": "../grapes"},
  {"name": "Teatro Colón", "addr": "Cerrito 628", "c": "ba", "cat": "latnivalo", "area": "Centro", "d": "A világ egyik legjobb akusztikájú operaháza.", "img": "colon", "own": 1},
  {"name": "El Ateneo Grand Splendid", "addr": "Av. Santa Fe 1860", "c": "ba", "cat": "latnivalo", "area": "Recoleta", "d": "Egykori színházból lett könyvesbolt – a világ egyik legszebbje.", "img": "ateneo", "own": 1},
  {"name": "Recoleta temető", "addr": "Junín 1760", "c": "ba", "cat": "latnivalo", "area": "Recoleta", "d": "Evita sírja és díszes családi kripták.", "img": "../recoleta", "own": 1, "m": "recoleta"},
  {"name": "Palacio Barolo", "addr": "Av. de Mayo 1370", "c": "ba", "cat": "latnivalo", "area": "Avenida de Mayo", "d": "Dante Isteni színjátéka ihlette épület, kilátóval.", "img": "barolo", "own": 1, "m": "barolo"},
  {"name": "Casa Rosada", "addr": "Balcarce 78", "c": "ba", "cat": "latnivalo", "area": "Plaza de Mayo", "d": "Az elnöki palota a Plaza de Mayón.", "img": "casa_rosada", "own": 1, "m": "casa rosada"},
  {"name": "Obelisco", "addr": "Av. Corrientes y 9 de Julio", "c": "ba", "cat": "latnivalo", "area": "Centro", "d": "A város jelképe a 9 de Julio sugárúton.", "img": "../ba", "own": 1},
  {"name": "Caminito", "addr": "Caminito, La Boca", "c": "ba", "cat": "latnivalo", "area": "La Boca", "d": "A színes házas utca La Bocában.", "img": "caminito", "own": 1, "m": "la boca"},
  {"name": "La Bombonera", "addr": "Brandsen 805", "c": "ba", "cat": "latnivalo", "area": "La Boca", "d": "A Boca Juniors stadionja.", "img": "bombonera", "own": 1, "m": "la boca"},
  {"name": "San Telmo", "addr": "San Telmo", "c": "ba", "cat": "latnivalo", "area": "San Telmo", "d": "Macskaköves óváros, vasárnap bolhapiac a Defensa utcán.", "img": "../san_telmo", "own": 1},
  {"name": "Puerto Madero", "addr": "Puerto Madero", "c": "ba", "cat": "latnivalo", "area": "Puerto Madero", "d": "Felújított kikötői promenád.", "img": null, "m": "puerto madero"},
  {"name": "El Rosedal", "addr": "Av. Infanta Isabel, Palermo", "c": "ba", "cat": "latnivalo", "area": "Palermo", "d": "Rózsakert a palermói parkokban – a helyi „Margitsziget”.", "img": "rosedal", "own": 1},
  {"name": "Jardín Japonés", "addr": "Av. Casares 3450", "c": "ba", "cat": "latnivalo", "area": "Palermo", "d": "Japánkert tavakkal, hidakkal (fizetős).", "img": "jardin_japones", "own": 1, "m": "japán|japan"},
  {"name": "Feria de Mataderos", "addr": "Av. de los Corrales y Lisandro de la Torre", "c": "ba", "cat": "latnivalo", "area": "Mataderos", "d": "Gaucsó-vásár népzenével, főleg hétvégén.", "img": "mataderos", "own": 1},
  {"name": "Parque General San Martín", "addr": "Av. Emilio Civit, Mendoza", "c": "mendoza", "cat": "latnivalo", "area": "Mendoza", "d": "Óriási városi park a díszkapukkal.", "img": "portones", "own": 1},
  {"name": "Cerro de la Gloria", "addr": "Cerro de la Gloria, Mendoza", "c": "mendoza", "cat": "latnivalo", "area": "Mendoza", "d": "Emlékmű-domb kilátással a városra.", "img": "cerro_gloria", "own": 1},
  {"name": "Fuente de los Continentes", "addr": "Parque General San Martín, Mendoza", "c": "mendoza", "cat": "latnivalo", "area": "Mendoza", "d": "Szökőkút a San Martín parkban.", "img": "fuente", "own": 1},
  {"name": "Plaza Independencia", "addr": "Gral. Espejo 300, Mendoza", "c": "mendoza", "cat": "latnivalo", "area": "Mendoza centrum", "d": "A belváros fő tere.", "img": "plaza_indep", "own": 1},
  {"name": "Parque Provincial Aconcagua", "addr": "RN7, Puente del Inca", "c": "hegyek", "cat": "kirandulas", "area": "Andok", "d": "Amerika legmagasabb csúcsa – az okt. 16-i túra célja.", "img": "../aconcagua", "own": 1, "m": "aconcagua"},
  {"name": "Puente del Inca", "addr": "Puente del Inca, Mendoza", "c": "hegyek", "cat": "kirandulas", "area": "Andok", "d": "Természetes kőhíd színes ásványi lerakódásokkal.", "img": "puente_inca", "own": 1, "m": "aconcagua"},
  {"name": "Cristo Redentor de los Andes", "addr": "Paso de Uspallata", "c": "hegyek", "cat": "kirandulas", "area": "Chilei határ", "d": "Krisztus-szobor a hágón, közel 4000 m-en.", "img": "cristo", "own": 1},
  {"name": "Quebrada del Río Vacas", "addr": "Punta de Vacas", "c": "hegyek", "cat": "kirandulas", "area": "Andok", "d": "Az Aconcagua park egyik völgye.", "img": "../andes"},
  {"name": "Mirador La Ventana", "addr": "Ruta Provincial 52, Uspallata", "c": "hegyek", "cat": "kirandulas", "area": "Uspallata", "d": "Kilátópont Uspallata felett.", "img": "uspallata"},
  {"name": "Termas de Cacheuta", "addr": "Cacheuta", "c": "hegyek", "cat": "kirandulas", "area": "Cacheuta", "d": "Termálfürdő a hegyekben.", "img": "cacheuta", "own": 1},
  {"name": "Cañón del Atuel", "addr": "RP173, San Rafael", "c": "hegyek", "cat": "kirandulas", "area": "San Rafael (messze)", "d": "Látványos kanyon – egész napos kirándulás.", "img": "atuel", "own": 1},
  {"name": "Laguna Pozo de las Ánimas", "addr": "Malargüe", "c": "hegyek", "cat": "kirandulas", "area": "Malargüe (messze)", "d": "Különleges víznyelő-tavak, nagyon messze délen.", "img": null},
];

const PLACE_PHOTO_CREDITS = {"don_julio": "Roberto Fiadone (CC BY 4.0)", "la_cabrera": "Madeleine Holland (CC BY 2.0)", "tortoni": "Bernard Gagnon (CC BY-SA 4.0)", "guerrin": "Roberto Fiadone (CC BY-SA 4.0)", "cadore": "Roberto Fiadone (CC BY-SA 4.0)", "mercado_mza": "Miguel (CC BY-SA 2.0)", "mercado_st": "ProtoplasmaKid (CC BY-SA 4.0)", "th_asado": "Aleposta (CC BY-SA 4.0)", "th_steak": "Yotam Nachum (CC0)", "th_chori": "Horacio Cambeiro (CC BY 3.0)", "th_empanada": "Horacio Cambeiro (CC BY-SA 3.0)", "th_coffee": "Ivanmartinez (CC BY-SA 3.0)", "th_beer": "Dangelin5 (CC BY-SA 3.0)", "th_icecream": "AlphaLemur (CC BY-SA 4.0)", "th_pizza": "Horacio Cambeiro (CC BY 3.0)", "colon": "Bernard Gagnon (CC BY-SA 4.0)", "ateneo": "Sombra Inquieta (CC BY-SA 4.0)", "rosedal": "ElGuruCesar (CC BY-SA 4.0)", "barolo": "Tadeo GV (CC BY-SA 4.0)", "casa_rosada": "Diego Delso (CC BY-SA 3.0)", "caminito": "Sombra Inquieta (CC BY-SA 4.0)", "bombonera": "Matibro (CC BY-SA 4.0)", "jardin_japones": "Roberto Fiadone (CC BY-SA 4.0)", "mataderos": "Carlos Adampol Galindo from DF, México (CC BY-SA 2.0)", "portones": "nano4773 (CC BY-SA 3.0)", "cerro_gloria": "ElGuruCesar (CC BY-SA 4.0)", "fuente": "Veronica Johansen (CC BY-SA 3.0)", "plaza_indep": "Itsmemarttin (CC BY-SA 3.0)", "cristo": "Alejandra Cartamil (CC BY-SA 4.0)", "puente_inca": "Bernard Gagnon (CC BY-SA 4.0)", "cacheuta": "Cobosch33 (CC BY-SA 4.0)", "atuel": "Pablo D. Flores (CC BY-SA 2.5)", "potrerillos": "Mauricio V. Genta (CC BY-SA 4.0)", "uspallata": "Richard Avis (CC BY-SA 2.0)"};
